version: '3.9'
services:
  mysql:
    image: mysql:latest
    env_file:
      - ./env/mysql.env
    volumes:
      - 'data:/var/lib/mysql'
    ports:
      - '3306:3306'
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend.Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
volumes:
  data: